language: php
php:
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer self-update
  - yes '' | pecl install -f mongodb-1.1
  - composer install
script: ./vendor/bin/phpunit --coverage-clover clover.xml
after_success:
     - travis_retry php vendor/bin/coveralls -v
matrix:
  fast_finish: true
  allow_failures:
     - php: 7.1
